//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicePlanner.Resources.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServicePlanner.Resources.Language.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by Tyler Poradun..
        /// </summary>
        public static string About_Description {
            get {
                return ResourceManager.GetString("About.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About_Title {
            get {
                return ResourceManager.GetString("About.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        public static string About_Version {
            get {
                return ResourceManager.GetString("About.Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Planner is a tool that can be used to help plan church services. Select an option from the menu on the left to get started..
        /// </summary>
        public static string App_Description {
            get {
                return ResourceManager.GetString("App.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Planner.
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Date.
        /// </summary>
        public static string GeneralEditor_Controls_Date_Label {
            get {
                return ResourceManager.GetString("GeneralEditor.Controls.Date.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home_Navigation_Title {
            get {
                return ResourceManager.GetString("Home.Navigation.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Institution_Address_City_Label {
            get {
                return ResourceManager.GetString("Institution.Address.City.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Institution_Address_Country_Label {
            get {
                return ResourceManager.GetString("Institution.Address.Country.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string Institution_Address_PostalCode_Label {
            get {
                return ResourceManager.GetString("Institution.Address.PostalCode.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Institution_Address_Region_Label {
            get {
                return ResourceManager.GetString("Institution.Address.Region.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string Institution_Address_Street_Label {
            get {
                return ResourceManager.GetString("Institution.Address.Street.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Institution_Address_Title {
            get {
                return ResourceManager.GetString("Institution.Address.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Institution_General_Name_Label {
            get {
                return ResourceManager.GetString("Institution.General.Name.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string Institution_General_Phone_Label {
            get {
                return ResourceManager.GetString("Institution.General.Phone.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Details.
        /// </summary>
        public static string Institution_General_Title {
            get {
                return ResourceManager.GetString("Institution.General.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institution.
        /// </summary>
        public static string Institution_Menu_Title {
            get {
                return ResourceManager.GetString("Institution.Menu.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan your order of service with music and other items..
        /// </summary>
        public static string OrderOfService_Description {
            get {
                return ResourceManager.GetString("OrderOfService.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order of Service.
        /// </summary>
        public static string OrderOfService_Title {
            get {
                return ResourceManager.GetString("OrderOfService.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Service Item.
        /// </summary>
        public static string ServiceEditor_AddGeneralServiceItem {
            get {
                return ResourceManager.GetString("ServiceEditor.AddGeneralServiceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Song.
        /// </summary>
        public static string ServiceEditor_AddSongServiceItem {
            get {
                return ResourceManager.GetString("ServiceEditor.AddSongServiceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate PDF.
        /// </summary>
        public static string ServiceEditor_GeneratePdf_Label {
            get {
                return ResourceManager.GetString("ServiceEditor.GeneratePdf.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change me.
        /// </summary>
        public static string ServiceEditor_ItemEditor_Default {
            get {
                return ResourceManager.GetString("ServiceEditor.ItemEditor.Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service item.
        /// </summary>
        public static string ServiceEditor_ItemEditor_Label {
            get {
                return ResourceManager.GetString("ServiceEditor.ItemEditor.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Items.
        /// </summary>
        public static string ServiceEditor_ServiceEditor_Header {
            get {
                return ResourceManager.GetString("ServiceEditor.ServiceEditor.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song.
        /// </summary>
        public static string ServiceEditor_SongEditor_Number_Label {
            get {
                return ResourceManager.GetString("ServiceEditor.SongEditor.Number.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change me.
        /// </summary>
        public static string ServiceEditor_SongEditor_Title_Default {
            get {
                return ResourceManager.GetString("ServiceEditor.SongEditor.Title.Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string ServiceEditor_SongEditor_Title_Label {
            get {
                return ResourceManager.GetString("ServiceEditor.SongEditor.Title.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string ServiceWizard_Button_Back {
            get {
                return ResourceManager.GetString("ServiceWizard.Button.Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string ServiceWizard_Button_Finish {
            get {
                return ResourceManager.GetString("ServiceWizard.Button.Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string ServiceWizard_Button_Next {
            get {
                return ResourceManager.GetString("ServiceWizard.Button.Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Service.
        /// </summary>
        public static string ServiceWizard_Menu_Title {
            get {
                return ResourceManager.GetString("ServiceWizard.Menu.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Wizard.
        /// </summary>
        public static string ServiceWizard_Page_Title {
            get {
                return ResourceManager.GetString("ServiceWizard.Page.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string ServiceWizard_Step_Details_Title {
            get {
                return ResourceManager.GetString("ServiceWizard.Step.Details.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Details.
        /// </summary>
        public static string ServiceWizard_Step_General_Title {
            get {
                return ResourceManager.GetString("ServiceWizard.Step.General.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order of Service.
        /// </summary>
        public static string ServiceWizard_Step_OrderOfService_Title {
            get {
                return ResourceManager.GetString("ServiceWizard.Step.OrderOfService.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include random songs.
        /// </summary>
        public static string Songs_IncludeRandom {
            get {
                return ResourceManager.GetString("Songs.IncludeRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of songs in book.
        /// </summary>
        public static string Songs_NumberInBook {
            get {
                return ResourceManager.GetString("Songs.NumberInBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of songs to include in service.
        /// </summary>
        public static string Songs_NumberToInclude {
            get {
                return ResourceManager.GetString("Songs.NumberToInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs.
        /// </summary>
        public static string Songs_Title {
            get {
                return ResourceManager.GetString("Songs.Title", resourceCulture);
            }
        }
    }
}
