//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicePlanner.Resources.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServicePlanner.Resources.Language.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Planner is a tool that can be used to help plan church services. Select an option from the menu on the left to get started..
        /// </summary>
        internal static string App_Description {
            get {
                return ResourceManager.GetString("App.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Planner.
        /// </summary>
        internal static string App_Title {
            get {
                return ResourceManager.GetString("App.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home_Navigation_Title {
            get {
                return ResourceManager.GetString("Home.Navigation.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan your order of service with music and other items..
        /// </summary>
        internal static string OrderOfService_Description {
            get {
                return ResourceManager.GetString("OrderOfService.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order of Service.
        /// </summary>
        internal static string OrderOfService_Title {
            get {
                return ResourceManager.GetString("OrderOfService.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Service Item.
        /// </summary>
        internal static string ServiceEditor_AddGeneralServiceItem {
            get {
                return ResourceManager.GetString("ServiceEditor.AddGeneralServiceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Song.
        /// </summary>
        internal static string ServiceEditor_AddSongServiceItem {
            get {
                return ResourceManager.GetString("ServiceEditor.AddSongServiceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change me.
        /// </summary>
        internal static string ServiceEditor_ItemEditor_Default {
            get {
                return ResourceManager.GetString("ServiceEditor.ItemEditor.Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service item.
        /// </summary>
        internal static string ServiceEditor_ItemEditor_Label {
            get {
                return ResourceManager.GetString("ServiceEditor.ItemEditor.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Items.
        /// </summary>
        internal static string ServiceEditor_ServiceEditor_Header {
            get {
                return ResourceManager.GetString("ServiceEditor.ServiceEditor.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song.
        /// </summary>
        internal static string ServiceEditor_SongEditor_Label {
            get {
                return ResourceManager.GetString("ServiceEditor.SongEditor.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include random songs.
        /// </summary>
        internal static string Songs_IncludeRandom {
            get {
                return ResourceManager.GetString("Songs.IncludeRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of songs in book.
        /// </summary>
        internal static string Songs_NumberInBook {
            get {
                return ResourceManager.GetString("Songs.NumberInBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of songs to include in service.
        /// </summary>
        internal static string Songs_NumberToInclude {
            get {
                return ResourceManager.GetString("Songs.NumberToInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs.
        /// </summary>
        internal static string Songs_Title {
            get {
                return ResourceManager.GetString("Songs.Title", resourceCulture);
            }
        }
    }
}
